# docker-compose.yml (в корне bank_loan_app)
services:
  backend:
    build:
      context: .               # контекст — весь проект
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    # монтируем backend в /backend, frontend в /frontend
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend
    working_dir: /backend   # теперь работаем в /backend
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: