services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: docker_bank_image
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend
    working_dir: /backend
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: